name: Terraform Apply

on:
  pull_request:
    types:
      - closed

jobs:
  apply:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -backend=false

      - run: terraform apply -auto-approve || true